INSERT INTO Inneh�llsklassificering(namn, beskrivning) 
VALUES
('Alcohol Reference','Reference to and/or images of alcoholic beverages'),
('Animated Blood','Discolored and/or unrealistic depictions of blood'),
('Blood','Depictions of blood'),
('Blood and Gore','Depictions of blood or the mutilation of body parts'),
('Cartoon Violence','Violent actions involving cartoon-like situations and characters. May include violence where a character is unharmed after the action has been inflicted'),
('Comic Mischief','Depictions or dialogue involving slapstick or suggestive humor'),
('Crude Humor','Depictions or dialogue involving vulgar antics, including “bathroom” humor'),
('Drug Reference','Reference to and/or images of illegal drugs'),
('Fantasy Violence','Violent actions of a fantasy nature, involving human or non-human characters in situations easily distinguishable from real life'),
('Intense Violence','Graphic and realistic-looking depictions of physical conflict. May involve extreme and/or realistic blood, gore, weapons and depictions of human injury and death'),
('Language','Mild to moderate use of profanity'),
('Lyrics','Mild references to profanity, sexuality, violence, alcohol or drug use in music'),
('Mature Humor','Depictions or dialogue involving "adult" humor, including sexual references'),
('Nudity','Graphic or prolonged depictions of nudity'),
('Partial Nudity','Brief and/or mild depictions of nudity'),
('Real Gambling','Player can gamble, including betting or wagering real cash or currency'),
('Sexual Content','Non-explicit depictions of sexual behavior, possibly including partial nudity'),
('Sexual Themes','References to sex or sexuality'),
('Sexual Violence','Depictions of rape or other violent sexual acts'),
('Simulated Gambling','Player can gamble without betting or wagering real cash or currency'),
('Strong Language','Explicit and/or frequent use of profanity'),
('Strong Lyrics','Explicit and/or frequent references to profanity, sex, violence, alcohol or drug use in music Strong Sexual Content,Explicit and/or frequent depictions of sexual behavior, possibly including nudity Suggestive Themes,Mild provocative references or materials'),
('Tobacco Reference','Reference to and/or images of tobacco products'),
('Use of Alcohol','The consumption of alcoholic beverages'),
('Use of Drugs','The consumption or use of illegal drugs'),
('Use of Tobacco','The consumption of tobacco products'),
('Violence','Scenes involving aggressive conflict. May contain bloodless dismemberment'),
('Violent References','References to violent acts');
