INSERT INTO SpelInnehallsklassificering(innehallsklassificering,spel)
VALUES
('Blood',2),
('Cartoon Violence',2),
('Fantasy Violence',3),
('Violence',3),
('Fantasy Violence',4),
('Fantasy Violence',5),
('Fantasy Violence',6),
('Cartoon Violence',6),
('Cartoon Violence',7),
('Cartoon Violence',8),
('Animated Blood',8),
('Cartoon Violence',9),
('Cartoon Violence',11),
('Cartoon Violence',12),
('Animated Blood',12),
('Comic Mischief',13),
('Animated Blood',14),
('Cartoon Violence',14),
('Tobacco Reference',14),
('Cartoon Violence',15),
('Cartoon Violence',16),
('Fantasy Violence',18),
('Animated Blood',18),
('Cartoon Violence',20),
('Fantasy Violence',21),
('Animated Blood',21),
('Alcohol Reference',21),
('Language',21),
('Partial Nudity',21),
('Use of Drugs',21),
('Use of Alcohol',21),
('Use of Alcohol',22),
('Language',22),
('Partial Nudity',22),
('Cartoon Violence',22),
('Cartoon Violence',23),
('Cartoon Violence',24),
('Cartoon Violence',25);
